/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tencent_qcloud_solibtest_JNITest */

#ifndef _Included_com_tencent_qcloud_solibtest_JNITest
#define _Included_com_tencent_qcloud_solibtest_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tencent_qcloud_solibtest_JNITest
 * Method:    test1
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_tencent_qcloud_solibtest_JNITest_test1
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_tencent_qcloud_solibtest_JNITest
 * Method:    test2
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_tencent_qcloud_solibtest_JNITest_test2
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
